
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    #password: cdr++2019
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8